version: 2

sources:
  - name: raw_stack_exchange_data
    description: "Raw Stack Exchange tables loaded into the warehouse."
    tables:
      - name: users
        config:
          loaded_at_field: creation_date
          freshness:
            warn_after:
              count: 24
              period: hour
            error_after:
              count: 48
              period: hour
          
        description: "Raw users data from the Stack Exchange dataset."
        columns:
          - name: user_id
            description: "Unique identifier for a user."
            tests:
              - not_null
              - unique
      - name: questions
        config:
          loaded_at_field: last_activity_date
          freshness:
            warn_after:
              count: 24
              period: hour
            error_after:
              count: 48
              period: hour
      - name: answers
        config:
          loaded_at_field: last_activity_date
          freshness:
            warn_after:
              count: 24
              period: hour
            error_after:
              count: 48
              period: hour
        description: "Raw answers data from the Stack Exchange dataset."
        columns:
          - name: answer_id
            description: "Unique identifier for an answer."
            tests:
              - not_null
              - unique
      - name: comments
        config:
          loaded_at_field: creation_date
          freshness:
            warn_after:
              count: 24
              period: hour
            error_after:
              count: 48
              period: hour
        description: "Raw comments data from the Stack Exchange dataset."
        columns:
          - name: comment_id
            description: "Unique identifier for a comment."
            tests:
              - not_null
              - unique
      - name: tags
        description: "Raw tags data from the Stack Exchange dataset."
        columns:
          - name: name
            description: "Tag name in the raw dataset."
            tests:
              - not_null
              - unique
      - name: badges
        description: "Raw badges data from the Stack Exchange dataset."
        columns:
          - name: badge_id
            description: "Unique identifier for a badge award."
            tests:
              - not_null
              - unique
